config/routes.rb
YavuSurveys::Engine.routes.draw do
  resources :surveys do
    member do
      get 'enable'
      get 'disable'
    end
    collection do
      get 'search'
    end
  end
end

app/models/yavu_surveys/answer.rb
module YavuSurveys
  class Answer < ActiveRecord::Base
    belongs_to :survey

    validates :title, presence: true
    validates :base_value, presence: true

    # Attributes to be exported for API
    set_api_resource id: :id,
      title: :title,
      base_value: :base_value,
      survey: ->(_) { survey.id },
      vote_count: ->(_) { vote_count }

    def voted?(user)
      Vote.exists?(self, user)
    end

    def vote_count(add_base: true)
      votes.size + (add_base ? base_value : 0)
    end

    def vote(user)
      Vote.add self, user
    end

    def votes
      Vote.from self
    end
  end
end

app/models/yavu_surveys/survey.rb
module YavuSurveys
  class Survey < ActiveRecord::Base
    has_many :answers
    has_and_belongs_to_many :sections, foreign_key: 'yavu_surveys_survey_id'
    accepts_nested_attributes_for :answers, allow_destroy: true

    validates :question, presence: true
    validates :answers, presence: true
    validates :sections, presence: true

    after_touch :touch_answers

    default_scope ->{ order(created_at: :desc) }

    def self.active(in_section: nil)
      Rails.cache.fetch("active", expires: YavuSettings.cache.backend.expiration_time.minutes) do
        if in_section
          includes(:sections).where('sections.id' => in_section.id, :active => true)
        else
          where(active: true)
        end.first
      end
    end

    # Attributes to be exported for API
    set_api_resource id: :question,
      question: :question,
      date: :date,
      voting_allowed: :voting_allowed,
      total_votes: :total_votes,
      answers: :answers

    def has_voted?(user)
      answers.any? { |a| a.voted? user }
    end

    def self.search(q)
      where 'question LIKE :query', query: "%#{q}%"
    end

    def total_votes
      answers.inject(0) { |total, answer| total + answer.vote_count }
    end

    def vote_for(answer, user)
      if answers.include?(answer) && !has_voted?(user) && active && voting_allowed
        answer.vote(user); touch; true
      else
        false
      end
    end

    def visible?
      true
    end

    def date
      created_at
    end

    def to_s
      question
    end

    protected

    def touch_answers
      answers.each &:touch
    end
  end
end

app/models/yavu_surveys/vote.rb
module YavuSurveys
  class Vote
    include Mongoid::Document

    field :a, as: :answer, type: Integer
    field :u, as: :user, type: String

    index a: -1
    index u:  1

    validates_presence_of :answer
    validates_presence_of :user

    def self.from(answer)
      where(answer: key_field_for(answer))
    end

    def self.add(answer, user)
      create(answer: key_field_for(answer), user: key_field_for(user))
    end

    def self.exists?(answer, user)
      where(answer: key_field_for(answer), user: key_field_for(user)).exists?
    end

    private

    def self.key_field_for(object)
      if object.is_a? String
        object
      else
        object.id
      end
    end
  end
end

app/controllers/yavu_surveys/application_controller.rb
module YavuSurveys
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/yavu_surveys/surveys_controller.rb
require_dependency "yavu_surveys/application_controller"

module YavuSurveys
  class SurveysController < ApplicationController
    before_action :set_survey, only: [ :edit, :update, :destroy, :enable, :disable ]

    def index
      @surveys = Survey.all
    end

    def search
      query = params[:q]
      matches = Survey.search query
      render json: matches.map { |survey| Hash[id: survey.id.to_s, text: survey.question] }
    end

    def new
      @survey = Survey.new
    end

    def edit
      render layout: !request.xhr?
    end

    def create
      @survey = Survey.new survey_params
      if @survey.save
        redirect_to surveys_path, notice: I18n.t('yavu_surveys/surveys.new.messages.success')
      else
        render action: 'new', layout: !request.xhr?
      end
    end

    def update
      if @survey.update(survey_params)
        redirect_to surveys_path, notice: I18n.t('yavu_surveys/surveys.edit.messages.success')
      else
        render action: 'edit', layout: !request.xhr?
      end
    end

    def enable
      @survey.update(active: true)
      redirect_to surveys_path, notice: I18n.t('yavu_surveys/surveys.enable.messages.success')
    end

    def disable
      @survey.update(active: false)
      redirect_to surveys_path, notice: I18n.t('yavu_surveys/surveys.disable.messages.success')
    end

    def destroy
      message = if @survey.destroy
        I18n.t('yavu_surveys/surveys.destroy.messages.success')
      else
        I18n.t('yavu_surveys/surveys.destroy.messages.failure')
      end
      redirect_to surveys_path, notice: message
    end

    private

    def survey_params
      params.require(:survey).permit(:question, :voting_allowed, :active, section_ids: [], answers_attributes: [:id, :title, :base_value, :_destroy])
    end

    def set_survey
      @survey = Survey.find(params[:id])
    end
  end
end

app/helpers/yavu_surveys/application_helper.rb
module YavuSurveys
  module ApplicationHelper
    def title(content = nil, &block)
      content = capture(&block) if block_given?
      content_for :title, content.html_safe
      content
    end

    def render_flashes
      render partial: 'shared/flashes' if flash.any?
    end

    def render_form_errors(source)
      render(partial: "shared/form_errors", locals: { errors: source.errors, model_name: t("mongoid.models.#{source.class.name.to_s.downcase}")}) unless source.errors.nil?
    end

    def date_with_format(datetime, date_format = :default)
      I18n.l datetime.to_date, format: date_format unless datetime.nil?
    end

    def time_with_format(datetime, time_format = :default)
      I18n.l datetime.to_time, format: time_format unless datetime.nil?
    end
  end
end

app/helpers/yavu_surveys/surveys_helper.rb
module YavuSurveys
  module SurveysHelper
  end
end

app/views/yavu_surveys/shared/_flashes.html.erb
<div class="row">
  <div class="large-12 columns">
    <% if flash[:notice] %>
      <div class="alert-box success" data-alert>
        <%= flash[:notice] || @notice %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:info] %>
      <div class="alert-box" data-alert>
        <%= flash[:info] || @info %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:alert] || flash[:error] %>
      <div class="alert-box alert" data-alert>
        <%= flash[:alert] || flash[:error] || @error %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:announcement_error] %>
      <div class="alert-box alert" data-alert>
        <%= flash[:announcement_error] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
    <% if flash[:announcement_notice] %>
      <div class="alert-box notice" data-alert>
        <%= flash[:announcement_notice] %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/yavu_surveys/shared/_form_errors.erb
<% if errors.any? %>
  <div id="error_explanation" class="panel radius alert row">
    <h5><%= t('form.shared.error_message', { error_count: pluralize(errors.count, t('form.shared.error')), model_name: model_name }) %></h5>

    <% errors.full_messages.each do |msg| %>
      <div class="error-msg large-11 columns large-offset-1"><%= msg %></div>
    <% end %>
  </div>
<% end %>

app/views/yavu_surveys/surveys/_answer_fields.html.erb
<div class="row">
  <div class="large-6 columns">
    <%= f.label :title, t('activerecord.attributes.yavu_surveys/answer.title') %>
    <%= f.text_field :title %>
  </div>
  <div class="large-2 large-offset-1 columns">
    <%= f.label :base_value, t('activerecord.attributes.yavu_surveys/answer.base_value') %>
    <%= f.number_field :base_value %>
  </div>
  <div class="large-1 large-offset-1 columns ">
    <%= f.label :actions, raw("&nbsp;") %>
    <%= f.link_to_remove t('activerecord.actions.yavu_surveys/answer.destroy'), { class: 'action button small radius alert' } %>
  </div>
</div>

app/views/yavu_surveys/surveys/_form.html.erb
<div class="form-container">
  <%= nested_form_for(@survey) do |f| %>

    <%= render_form_errors @survey  %>

    <div class="field-container panel">
      <p class="field">
        <%= f.label :question, t('activerecord.attributes.yavu_surveys/survey.question') %>
        <%= f.text_field :question %>
      </p>
      <div class="row">
        <p class="field large-4 columns">
          <%= f.label :active, t('activerecord.attributes.yavu_surveys/survey.active') %>
          <%= f.check_box :active %>
        </p>
        <p class="field large-4 end columns">
          <%= f.label :voting_allowed, t('activerecord.attributes.yavu_surveys/survey.voting_allowed') %>
          <%= f.check_box :voting_allowed %>
        </p>
      </div>
      <p class="field">
        <%= f.label :sections, t('activerecord.attributes.yavu_surveys/survey.sections') %>
        <%= collection_select2_select :survey, :section_ids, Section.visible, :id, :to_s, {}, { multiple: true } %>
      </p>
      <p class="field">
        <%= f.label :question, t('activerecord.attributes.yavu_surveys/survey.answers') %>
        <div id="answers" class="field-container panel">
          <%= f.fields_for :answers, @survey.answers %>
        </div>
      </p>
      <div>
        <%= f.link_to_add t('activerecord.actions.yavu_surveys/survey.add_answer'), :answers, { class: 'action button radius', data: { target: "#answers" } } %>
      </div>
    </div>

    <ul class="form-actions">
      <li class="right"><%= f.submit class: "action button radius success" %></li>
    </ul>

  <% end %>
</div>

app/views/yavu_surveys/surveys/edit.html.erb
<h1><%= t('yavu_surveys/surveys.edit.title') %></h1>

<%= render 'form' %>

<ul class="context-actions">
  <li><%= link_to t('activerecord.actions.shared.back'), surveys_path, class: 'button radius secondary' %></li>
</ul>

app/views/yavu_surveys/surveys/index.html.erb
<div class="row crud-header">
  <h1 class="large-12 columns">
    <%= title t('yavu_surveys/surveys.list.title') %>
  </h1>

  <%= render_flashes %>

<ul class="context-actions">
  <li class="right"><%= link_to t('activerecord.actions.yavu_surveys/survey.new'), new_survey_path, class: 'action button radius success' %></li>
</ul>

<span>
  Última encuesta vigente: <%= YavuSurveys::Survey.active.try(:question) || 'Ninguna' %>
<span>

<table class="large-12 crud-table">
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.yavu_surveys/survey.question' %></th>
      <th data-tooltip aria-haspopup="true" class="has-tip tip-top" title="<%= t 'activerecord.attributes.yavu_surveys/survey.answers_tip' %>"><%= t 'activerecord.attributes.yavu_surveys/survey.answers' %></th>
      <th><%= t 'activerecord.attributes.yavu_surveys/survey.date' %></th>
      <th><%= t 'activerecord.attributes.yavu_surveys/survey.active' %></th>
      <th><%= raw "&nbsp;" %></th>
    </tr>
  </thead>

  <tbody>
    <%= content_tag_for(:tr, @surveys) do |survey| %>
      <td><%= survey.question %></td>
      <td>
        <% survey.answers.each do |answer| %>
          <div class="row">
            <div class="large-3 columns"><strong><%= answer.title %></strong></div>
            <div class="large-3 columns"><%= answer.vote_count %></div>
          </div>
        <% end %>
      </td>
      <td><%= date_with_format survey.created_at %></td>
      <td><%= render_boolean survey.active? %></td>
      <td>
        <a href="#" class="button small dropdown secondary radius" data-dropdown="action-dropdown-<%= survey.id %>">
          <%= t('activerecord.actions.shared.actions') %>
        </a>
        <ul class="f-dropdown" id="action-dropdown-<%= survey.id %>" <%= plugins mover: {} %> data-dropdown-content>
          <li class="success"><%= link_to t('activerecord.actions.shared.edit'), edit_survey_path(survey) %></li>
          <% if survey.active? %>
            <li><%= link_to t('activerecord.actions.shared.disable'), disable_survey_path(survey) %></li>
          <% else %>
            <li><%= link_to t('activerecord.actions.shared.enable'),  enable_survey_path(survey)  %></li>
          <% end %>
          <li class="divider"></li>
          <li class="alert"><%= link_to t('activerecord.actions.shared.destroy'), survey, method: :delete, data: { confirm: t('activerecord.actions.shared.confirmation.destroy') } %></li>
        </ul>
      </td>
    <% end %>
  </tbody>
</table>

app/views/yavu_surveys/surveys/new.html.erb
<h1><%= t('yavu_surveys/surveys.new.title') %></h1>

<%= render 'form' %>

<ul class="context-actions">
  <li><%= link_to t('activerecord.actions.shared.back'), surveys_path, class: 'button secondary radius' %></li>
</ul>